#Amount of inventory rows this type of bag of holding has.
#Range: 1 ~ 9
leather_bag_rows = 1
#Amount of inventory rows this type of bag of holding has.
#Range: 1 ~ 9
iron_bag_rows = 3
#Chance that one level of preservation will be lost on a bag of holding when dying.
#Range: 0.0 ~ 1.0
preservation_level_loss_chance = 1.0
#Amount of inventory rows this type of bag of holding has.
#Range: 1 ~ 9
golden_bag_rows = 6
#Require the player to be crouching to open the item bag menu via right-click.
sneak_to_open_bag = false

