
[client]
	#Color of cursed earth, pick #CC00FF classic style color, pick #222222 for brighter newage color, or any hex code color you would like.
	color_cursed_earth = "#CC00FF"
	#Color of cursed earth, pick #CC00FF classic style color, pick #222222 for brighter newage color, or any hex code color you would like.
	color_blessed_earth = "#00BCD4"

