// priority: 1000

function checkForBlockInCube(targetBlock, level, cubeSize, sx, sy, sz) {
  for (let x = -Math.abs(cubeSize); x <= cubeSize; x++) {
    for (let y = -Math.abs(cubeSize); y <= cubeSize; y++) {
      for (let z = -Math.abs(cubeSize); z <= cubeSize; z++) {
        const block = level.getBlock(sx + x, sy + y, sz + z);
        if (block.id === targetBlock) {
          return block;
        }
      }
    }
  }
  return "";
}

function swapItem(player, oldItem, newItem) {
  const inventory = player.inventory;
  for (let i = 0; i < inventory.containerSize; i++) {
    if (inventory.getItem(i) === oldItem) {
      inventory.setItem(i, newItem);
    }
  }
  player.sendInventoryUpdate();
}

global["unUnified"] = [
  "integrateddynamics:energy_battery",
  "integrateddynamics:energy_battery",
  "integrateddynamics:coal_generator",
  "integratedterminals:terminal_storage_portable",
  "integrateddynamics:coal_generator",
  "immersiveengineering:ore_aluminum",
  "immersiveengineering:deepslate_ore_aluminum",
  "mob_grinding_utils:dreadful_dirt",
  "mob_grinding_utils:delightful_dirt",
  "mob_grinding_utils:golden_egg",
  "mob_grinding_utils:rotten_egg",
  "mob_grinding_utils:nutritious_chicken_feed",
  "mob_grinding_utils:gm_chicken_feed_cursed",
  "immersiveengineering:stick_iron",
  "immersiveengineering:stick_aluminum",
  "immersiveengineering:stick_steel",
  "immersiveengineering:ingot_aluminum",
  "immersiveengineering:ingot_uranium",
  "mekanism:ingot_uranium",
  "immersiveengineering:ingot_lead",
  "immersiveengineering:ingot_nickel",
  "mffs:steel_ingot",
  "mekanism:steel_ingot",
  "mekanism:ingot_bronze",
  "mekanism:ingot_lead",
  "mekanism:ingot_tin",
  "immersiveengineering:ingot_steel",
  "immersiveengineering:plate_copper",
  "immersiveengineering:plate_aluminum",
  "immersiveengineering:plate_lead",
  "immersiveengineering:plate_silver",
  "immersiveengineering:plate_nickel",
  "immersiveengineering:plate_uranium",
  "immersiveengineering:plate_steel",
  "immersiveengineering:ingot_electrum",
  "immersiveengineering:plate_iron",
  "immersiveengineering:plate_gold",
  "pneumaticcraft:lubricant_bucket",
  "modern_industrialization:creosote_bucket",
  "immersiveengineering:nugget_silver",
  "mekanism:nugget_bronze",
  "immersiveengineering:nugget_uranium",
  "immersiveengineering:nugget_lead",
  "immersiveengineering:nugget_aluminum",
  "immersiveengineering:nugget_copper",
  "immersiveengineering:coke",
  "immersiveengineering:coal_coke",
  "immersiveengineering:dust_coke",
  "immersiveengineering:nugget_steel",
  "mekanism:nugget_steel",
  "immersiveengineering:nugget_electrum",
  "immersiveengineering:nugget_nickel",
  "mekanism:ingot_steel",
  "immersiveengineering:ingot_silver",
  "mffs:steel_compound",
  "mekanism:dust_steel",
  "immersiveengineering:dust_steel",
  "mekanism:dust_coal",
  "mekanism:dust_bronze",
  "immersiveengineering:dust_uranium",
  "mekanism:dust_uranium",
  "immersiveengineering:dust_lead",
  "mekanism:dust_lead",
  "mekanism:dust_tin",
  "immersiveengineering:dust_copper",
  "mekanism:salt",
  "mekanism:dust_sulfur",
  "immersiveengineering:dust_sulfur",
  "immersiveengineering:dust_wood",
  "immersiveengineering:dust_aluminum",
  "immersiveengineering:dust_silver",
  "immersiveengineering:dust_nickel",
  "immersiveengineering:dust_electrum",
  "mekanism:dust_diamond",
  "mekanism:dust_emerald",
  "mekanism:dust_lapis_lazuli",
  "mekanism:dust_quartz",
  "immersiveengineering:dust_iron",
  "immersiveengineering:dust_gold",
  "mekanism:dust_iron",
  "mekanism:dust_gold",
  "mekanism:dust_copper",
  "modern_industrialization:steel_hammer",
  "modern_industrialization:diamond_hammer",
  "modern_industrialization:iron_hammer",
  "modern_industrialization:netherite_hammer",
  "justhammers:netherite_impact_hammer",
  "justhammers:diamond_impact_hammer",
  "justhammers:gold_impact_hammer",
  "justhammers:iron_impact_hammer",
  "justhammers:stone_impact_hammer",
  "justhammers:stone_destructor_hammer",
  "justhammers:iron_destructor_hammer",
  "justhammers:diamond_destructor_hammer",
  "justhammers:gold_destructor_hammer",
  "justhammers:netherite_destructor_hammer",
  "justhammers:stone_reinforced_impact_hammer",
  "justhammers:iron_reinforced_impact_hammer",
  "justhammers:gold_reinforced_impact_hammer",
  "justhammers:diamond_reinforced_impact_hammer",
  "justhammers:netherite_reinforced_impact_hammer",
  "justhammers:netherite_reinforced_hammer",
  "justhammers:diamond_reinforced_hammer",
  "justhammers:gold_reinforced_hammer",
  "justhammers:iron_reinforced_hammer",
  "justhammers:stone_reinforced_hammer",
  "modern_industrialization:diesel_mining_drill",
  "immersiveengineering:raw_aluminum",
  "immersiveengineering:raw_block_aluminum",
  "jaopca:storage_blocks.flour",
  "modern_industrialization:deepslate_lignite_coal_ore",
  "modern_industrialization:lignite_coal_ore",
  "modern_industrialization:lignite_coal_block",
  "modern_industrialization:lignite_coal_crushed_dust",
  "modern_industrialization:lignite_coal_dust",
  "modern_industrialization:lignite_coal",
  "modern_industrialization:lignite_coal_tiny_dust",
  "ae2:silicon",
  "ae2:charger",
  "pneumaticcraft:biodiesel_bucket",
  "immersiveengineering:biodiesel_bucket",
  "immersiveengineering:diesel_bucket",
  "jaopca:storage_blocks.ender_pearl",
  "pamhc2foodcore:saltitem",
  "mekanism:block_salt",
  "pamhc2crops:coffeebeanseeditem",
  "pamhc2crops:coffeebeanitem",
  "actuallyadditions:wings_of_the_bats",
  "actuallyadditions:crate_small",
  "actuallyadditions:ender_star",
  "actuallyadditions:lamp_controller",
  "actuallyadditions:leaf_generator",
  "actuallyadditions:xp_solidifier",
  "actuallyadditions:solidified_experience",
  "actuallyadditions:lamp_cyan",
  "actuallyadditions:lamp_purple",
  "actuallyadditions:lamp_blue",
  "actuallyadditions:lamp_brown",
  "actuallyadditions:lamp_green",
  "actuallyadditions:lamp_red",
  "actuallyadditions:lamp_black",
  "actuallyadditions:lamp_light_gray",
  "actuallyadditions:lamp_gray",
  "actuallyadditions:lamp_pink",
  "actuallyadditions:lamp_lime",
  "actuallyadditions:lamp_yellow",
  "actuallyadditions:lamp_light_blue",
  "actuallyadditions:lamp_magenta",
  "actuallyadditions:lamp_orange",
  "actuallyadditions:lamp_white",
  "immersiveengineering:plate_electrum",
  "mekanism:nugget_tin",
  "mekanism:nugget_lead",
  "mekanism:nugget_uranium",
  "ae2:vibration_chamber",
  "ae2:crank",
  "jaopca:modern_industrialization_crushed_dusts.black_quartz",
  "jaopca:modern_industrialization_crushed_dusts.fluorite",
  "jaopca:dusts.black_quartz",
  "immersiveengineering:raw_silver",
  "mekanism:raw_tin",
  "mekanism:raw_lead",
  "immersiveengineering:raw_lead",
  "mekanism:raw_uranium",
  "immersiveengineering:raw_uranium",
  "immersiveengineering:raw_nickel",
  "solonion:lunchbox",
  "solonion:golden_lunchbox",
  "solonion:lunchbag",
  "extendedae:circuit_cutter",
  "extendedae:silicon_block"
];

global["hideOres"] = [
  "immersiveengineering:deepslate_ore_nickel",
  "mekanism:deepslate_tin_ore",
  "mekanism:tin_ore",
  "mekanism:deepslate_osmium_ore",
  "mekanism:uranium_ore",
  "mekanism:deepslate_uranium_ore",
  "immersiveengineering:ore_uranium",
  "immersiveengineering:deepslate_ore_uranium",
  "mekanism:lead_ore",
  "immersiveengineering:ore_nickel",
  "mekanism:deepslate_lead_ore",
  "immersiveengineering:ore_lead",
  "immersiveengineering:deepslate_ore_lead",
];

global["startingItems"] = [
  "5x minecraft:oak_sapling",
  "5x minecraft:carrot",
  "ftbquests:book",
];
